global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerting_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # REST API Downloader metrics
  - job_name: 'downloader'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Adjust port if needed
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Redis metrics (if using Redis)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # System metrics (node_exporter if available)
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']  # Optional: add node_exporter
    scrape_interval: 30s